services:
  app:
    container_name: "application-server"
    image: "us-east1-docker.pkg.dev/greg-vertex-ai-playground/gj-napari-xpra/napari-xpra:latest"
    restart: always
    volumes:
      - .:/workspace:cached
    ports:
      - '9876:9876'
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
networks:
  app-network:
    external: true
  