services:
  app:
    container_name: "application-server"
    image: "docker.io/library/kasmweb/only-office:1.15.0-rolling"
    restart: always
    volumes:
      - .:/workspace:cached
    ports:
      - '6901:6901'
    networks: 
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    environment:
      VNC_PW: "password"
      VNCOPTIONS: "-log *:stderr:100 -sslOnly false"
networks:
  app-network:
    external: true
