services:
  app:
    container_name: "application-server"
    image: "kasmweb/ubuntu-noble-desktop:1.16.0"
    restart: always
    volumes:
      - .:/workspace:cached
    ports:
      - '6901:6901'
    networks: 
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    environment:
      VNC_PW: "password"
      VNCOPTIONS: "-sslOnly false"
networks:
  app-network:
    external: true
